#### Find E and store it in dataset

In [9]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog
import seaborn as sns
import numpy as np

In [10]:
# Ask the user to select a folder containing the data files
root = tk.Tk()
root.withdraw()  # hide the main tkinter window
folder_path = filedialog.askdirectory(title="Please select the folder containing the data files: ")

In [17]:

# Find list of relative paths to .txt files in all the folders and subfolders of the selected folder
txt_files = []
for root_dir, dirs, files in os.walk(folder_path):
    for file in files:
        if file.endswith(".txt"):
            txt_files.append(os.path.relpath(os.path.join(root_dir, file), folder_path))


#remove those in Calib folder and those ending with position.txt
txt_files = [f for f in txt_files if "Calib" not in f and not f.endswith("position.txt")]

print("List of filtered .txt files:")
for f in txt_files:
    print(f)
print("\n")

# create a df to store the results
results_df = pd.DataFrame(columns=["Name", "Folder", "E[eff] (kPa)", "E[v=0.50] (kPa)"])


# read text file tracking line until you find line with info 
for l in range(len(txt_files)):
    path = os.path.join(folder_path, txt_files[l])
    results_df.loc[l, "Folder"] = os.path.dirname(txt_files[l])
    # Name is until "S-" in the filename
    results_df.loc[l, "Name"] = os.path.basename(txt_files[l]).split("S-")[0]
    with open(path, 'r', encoding='latin-1', errors='replace') as f:
        for i, line in enumerate(f):
            if "E[eff]" in line:
                results_df.loc[l, "E[eff] (kPa)"] = (float(line.strip().split('\t')[-1]))/1e3
            if "E[v=0.50]" in line:
                results_df.loc[l, "E[v=0.50] (kPa)"] = (float(line.strip().split('\t')[-1]))/1e3



# Add an index count per folder
display(results_df)

List of filtered .txt files:
A1.1\Indentations\A1.1 Indentation_001.txt
A1.1\Indentations\A1.1 Indentation_002.txt
A1.1\Indentations\A1.1 Indentation_003.txt
A1.1\Indentations\A1.1 Indentation_004.txt
A1.1\Indentations\A1.1 Indentation_005.txt
A1.1\Indentations\A1.1 Indentation_006.txt
A1.1\Indentations\A1.1 Indentation_007.txt
A1.1\Indentations\A1.1 Indentation_008.txt
A1.1\Indentations\A1.1 Indentation_009.txt
A1.1\Indentations\A1.1 Indentation_010.txt
A1.1\Indentations\A1.1 Indentation_011.txt
A1.1\Indentations\A1.1 Indentation_012.txt
A1.1\Indentations\A1.1 Indentation_013.txt
A1.1\Indentations\A1.1 Indentation_014.txt
A1.1\Indentations\A1.1 Indentation_015.txt
A1.1\Indentations\A1.1 Indentation_016.txt
A1.1\Indentations\A1.1 Indentation_017.txt
A1.1\Indentations\A1.1 Indentation_018.txt
A1.1\Indentations\A1.1 Indentation_019.txt
A1.1\Indentations\A1.1 Indentation_020.txt
A1.1\Indentations\A1.1 Indentation_021.txt
A1.1\Indentations\A1.1 Indentation_022.txt
A1.1\Indentations\A1.1 Indentation_023.txt
A1.1\Indentations\A1.1 Indentation_024.txt
A1.1\Indentations\A1.1 Indentation_025.txt
A1.1\Indentations\A1.1 Indentation_026.txt
A1.1\Indentations\A1.1 Indentation_027.txt
A1.1\Indentations\A1.1 Indentation_028.txt
A1.1\Indentations\A1.1 Indentation_029.txt
A1.1\Indentations\A1.1 Indentation_030.txt
A1.1\Indentations\A1.1 Indentation_031.txt
A1.1\Indentations\A1.1 Indentation_032.txt
A1.1\Indentations\A1.1 Indentation_033.txt
A1.1\Indentations\A1.1 Indentation_034.txt
A1.1\Indentations\A1.1 Indentation_035.txt
A1.1\Indentations\A1.1 Indentation_036.txt
A1.1\Indentations\A1.1 Indentation_037.txt
A1.1\Indentations\A1.1 Indentation_038.txt
A1.1\Indentations\A1.1 Indentation_039.txt
A1.1\Indentations\A1.1 Indentation_040.txt
A1.1\Indentations\A1.1 Indentation_041.txt
A1.2\Indentations\A1.2 Indentation_001.txt
A1.2\Indentations\A1.2 Indentation_002.txt
A1.2\Indentations\A1.2 Indentation_003.txt
A1.2\Indentations\A1.2 Indentation_004.txt
A1.2\Indentations\A1.2 Indentation_005.txt
A1.2\Indentations\A1.2 Indentation_006.txt
A1.2\Indentations\A1.2 Indentation_007.txt
A1.2\Indentations\A1.2 Indentation_008.txt
A1.2\Indentations\A1.2 Indentation_009.txt
A1.2\Indentations\A1.2 Indentation_010.txt
A1.2\Indentations\A1.2 Indentation_011.txt
A1.2\Indentations\A1.2 Indentation_012.txt
A1.2\Indentations\A1.2 Indentation_013.txt
A1.2\Indentations\A1.2 Indentation_014.txt
A1.2\Indentations\A1.2 Indentation_015.txt
A1.2\Indentations\A1.2 Indentation_016.txt
A1.2\Indentations\A1.2 Indentation_019.txt
A1.2\Indentations\A1.2 Indentation_020.txt
A1.2\Indentations\A1.2 Indentation_021.txt
B1.1\Indentations\B1.1 Indentation_001.txt
B1.1\Indentations\B1.1 Indentation_002.txt
B1.1\Indentations\B1.1 Indentation_003.txt
B1.1\Indentations\B1.1 Indentation_004.txt
B1.1\Indentations\B1.1 Indentation_005.txt
B1.1\Indentations\B1.1 Indentation_006.txt
B1.1\Indentations\B1.1 Indentation_007.txt
B1.1\Indentations\B1.1 Indentation_008.txt
B1.1\Indentations\B1.1 Indentation_009.txt
B1.1\Indentations\B1.1 Indentation_010.txt
B1.1\Indentations\B1.1 Indentation_011.txt
B1.1\Indentations\B1.1 Indentation_012.txt
B1.1\Indentations\B1.1 Indentation_013.txt
B1.1\Indentations\B1.1 Indentation_014.txt
B1.1\Indentations\B1.1 Indentation_015.txt
B1.1\Indentations\B1.1 Indentation_016.txt
B1.1\Indentations\B1.1 Indentation_017.txt
B1.1\Indentations\B1.1 Indentation_018.txt
B1.1\Indentations\B1.1 Indentation_019.txt
B1.1\Indentations\B1.1 Indentation_020.txt
B1.1\Indentations\B1.1 Indentation_021.txt
B1.1\Indentations\B1.1 Indentation_022.txt
B1.1\Indentations\B1.1 Indentation_023.txt
B1.1\Indentations\B1.1 Indentation_024.txt
B1.1\Indentations\B1.1 Indentation_025.txt
B1.1\Indentations\B1.1 Indentation_026.txt
B1.1\Indentations\B1.1 Indentation_027.txt
B1.2\Indentations\B1.2 Indentation_001.txt
B1.2\Indentations\B1.2 Indentation_002.txt
B1.2\Indentations\B1.2 Indentation_003.txt
B1.2\Indentations\B1.2 Indentation_004.txt
B1.2\Indentations\B1.2 Indentation_005.txt
B1.2\Indentations\B1.2 Indentation_007.txt
B1.2\Indentations\B1.2 Indentation_008.txt
B1.2\Indentations\B1.2 Indentation_009.txt
B1.2\Indentations\B1.2 Indentation_010.txt
B1.2\Indentations\B1.2 Indentation_011.txt
B1.2\Indentations\B1.2 Indentation_012.txt
B1.2\Indentations\B1.2 Indentation_013.txt
B1.2\Indentations\B1.2 Indentation_014.txt
B1.2\Indentations\B1.2 Indentation_015.txt
B1.2\Indentations\B1.2 Indentation_016.txt
B1.2\Indentations\B1.2 Indentation_017.txt
B1.2\Indentations\B1.2 Indentation_018.txt
B1.2\Indentations\B1.2 Indentation_019.txt
B1.2\Indentations\B1.2 Indentation_020.txt
B1.2\Indentations\B1.2 Indentation_021.txt
B1.2\Indentations\B1.2 Indentation_022.txt
B1.2\Indentations\B1.2 Indentation_023.txt
B1.2\Indentations\B1.2 Indentation_024.txt
B1.2\Indentations\B1.2 Indentation_025.txt
B1.2\Indentations\B1.2 Indentation_026.txt
B1.2\Indentations\B1.2 Indentation_027.txt
B1.2\Indentations\B1.2 Indentation_028.txt
B1.2\Indentations\B1.2 Indentation_029.txt
B1.2\Indentations\B1.2 Indentation_030.txt
B1.2\Indentations\B1.2 Indentation_031.txt
B1.2\Indentations\B1.2 Indentation_032.txt
B1.2\Indentations\B1.2 Indentation_034.txt
B1.2\Indentations\B1.2 Indentation_035.txt
B1.2\Indentations\B1.2 Indentation_036.txt
B1.2\Indentations\B1.2 Indentation_037.txt
B1.2\Indentations\B1.2 Indentation_038.txt
B1.2\Indentations\B1.2 Indentation_039.txt
B1.2\Indentations\B1.2 Indentation_040.txt
B1.2\Indentations\B1.2 Indentation_041.txt
B2.1\Indentations\B2.1 Indentation_001.txt
B2.1\Indentations\B2.1 Indentation_002.txt
B2.1\Indentations\B2.1 Indentation_003.txt
B2.1\Indentations\B2.1 Indentation_004.txt
B2.1\Indentations\B2.1 Indentation_005.txt
B2.1\Indentations\B2.1 Indentation_006.txt
B2.1\Indentations\B2.1 Indentation_007.txt
B2.1\Indentations\B2.1 Indentation_008.txt
B2.1\Indentations\B2.1 Indentation_009.txt
B2.1\Indentations\B2.1 Indentation_010.txt
B2.1\Indentations\B2.1 Indentation_011.txt
B2.1\Indentations\B2.1 Indentation_012.txt
B2.1\Indentations\B2.1 Indentation_013.txt
B2.1\Indentations\B2.1 Indentation_014.txt
B2.1\Indentations\B2.1 Indentation_015.txt
B2.1\Indentations\B2.1 Indentation_016.txt
B2.1\Indentations\B2.1 Indentation_017.txt
B2.1\Indentations\B2.1 Indentation_018.txt
B2.1\Indentations\B2.1 Indentation_019.txt
B2.1\Indentations\B2.1 Indentation_020.txt
B2.1\Indentations\B2.1 Indentation_021.txt
B2.1\Indentations\B2.1 Indentation_022.txt
B2.1\Indentations\B2.1 Indentation_023.txt
B2.1\Indentations\B2.1 Indentation_024.txt
B2.1\Indentations\B2.1 Indentation_025.txt
B2.1\Indentations\B2.1 Indentation_026.txt
B2.2\Indentations\B2.2 Indentation_001.txt
B2.2\Indentations\B2.2 Indentation_002.txt
B2.2\Indentations\B2.2 Indentation_003.txt
B2.2\Indentations\B2.2 Indentation_004.txt
B2.2\Indentations\B2.2 Indentation_005.txt
B2.2\Indentations\B2.2 Indentation_006.txt
B2.2\Indentations\B2.2 Indentation_007.txt
B2.2\Indentations\B2.2 Indentation_008.txt
B2.2\Indentations\B2.2 Indentation_009.txt
B2.2\Indentations\B2.2 Indentation_010.txt
B2.2\Indentations\B2.2 Indentation_011.txt
B2.2\Indentations\B2.2 Indentation_012.txt
B2.2\Indentations\B2.2 Indentation_013.txt
B2.2\Indentations\B2.2 Indentation_014.txt
B2.2\Indentations\B2.2 Indentation_015.txt
B2.2\Indentations\B2.2 Indentation_016.txt
B2.2\Indentations\B2.2 Indentation_017.txt
B2.2\Indentations\B2.2 Indentation_018.txt
B2.2\Indentations\B2.2 Indentation_019.txt
B2.2\Indentations\B2.2 Indentation_020.txt
B2.2\Indentations\B2.2 Indentation_021.txt
B2.2\Indentations\B2.2 Indentation_022.txt
B2.2\Indentations\B2.2 Indentation_023.txt
B2.2\Indentations\B2.2 Indentation_024.txt
B2.2\Indentations\B2.2 Indentation_025.txt
B2.2\Indentations\B2.2 Indentation_026.txt
B2.2\Indentations\B2.2 Indentation_027.txt
B2.2\Indentations\B2.2 Indentation_028.txt
B2.2\Indentations\B2.2 Indentation_029.txt
B2.2\Indentations\B2.2 Indentation_030.txt
B2.2\Indentations\B2.2 Indentation_031.txt
B2.2\Indentations\B2.2 Indentation_032.txt
B2.2\Indentations\B2.2 Indentation_033.txt
B2.2\Indentations\B2.2 Indentation_034.txt
B2.2\Indentations\B2.2 Indentation_035.txt
B2.2\Indentations\B2.2 Indentation_036.txt
B2.2\Indentations\B2.2 Indentation_037.txt
B2.2\Indentations\B2.2 Indentation_038.txt
B2.2\Indentations\B2.2 Indentation_039.txt
B2.2\Indentations\B2.2 Indentation_040.txt
B2.2\Indentations\B2.2 Indentation_041.txt
B2.2\Indentations\B2.2 Indentation_042.txt
B2.2\Indentations\B2.2 Indentation_043.txt
B2.2\Indentations\B2.2 Indentation_044.txt
B2.2\Indentations\B2.2 Indentation_045.txt
B2.2\Indentations\B2.2 Indentation_046.txt
B2.2\Indentations\B2.2 Indentation_047.txt
B2.2\Indentations\B2.2 Indentation_048.txt
B2.2\Indentations\B2.2 Indentation_049.txt
B2.2\Indentations\B2.2 Indentation_050.txt
B2.2\Indentations\B2.2 Indentation_051.txt
B2.2\Indentations\B2.2 Indentation_052.txt
B2.2\Indentations\B2.2 Indentation_053.txt
B2.2\Indentations\B2.2 Indentation_054.txt
B2.2\Indentations\B2.2 Indentation_055.txt
B2.2\Indentations\B2.2 Indentation_056.txt
B2.2\Indentations\B2.2 Indentation_057.txt
B2.2\Indentations\B2.2 Indentation_058.txt
B2.2\Indentations\B2.2 Indentation_059.txt
B2.2\Indentations\B2.2 Indentation_060.txt
B2.2\Indentations\B2.2 Indentation_061.txt
B2.2\Indentations\B2.2 Indentation_062.txt
B2.2\Indentations\B2.2 Indentation_063.txt
B2.2\Indentations\B2.2 Indentation_064.txt
B2.2\Indentations\B2.2 Indentation_065.txt
B2.2\Indentations\B2.2 Indentation_066.txt
B2.2\Indentations\B2.2 Indentation_067.txt
B2.2\Indentations\B2.2 Indentation_068.txt
B2.2\Indentations\B2.2 Indentation_069.txt
B2.2\Indentations\B2.2 Indentation_070.txt
B2.2\Indentations\B2.2 Indentation_071.txt
B2.2\Indentations\B2.2 Indentation_072.txt
B2.2\Indentations\B2.2 Indentation_073.txt
B2.2\Indentations\B2.2 Indentation_074.txt
B2.2\Indentations\B2.2 Indentation_075.txt
B2.2\Indentations\B2.2 Indentation_076.txt
B2.2\Indentations\B2.2 Indentation_077.txt

,Name,Folder,E[eff] (kPa),E[v=0.50] (kPa)
0,A1.1 Indentation_001.txt,A1.1\Indentations,4607213.376255,3455410.032191
1,A1.1 Indentation_002.txt,A1.1\Indentations,4607213.376255,3455410.032191
2,A1.1 Indentation_003.txt,A1.1\Indentations,NaN,NaN
3,A1.1 Indentation_004.txt,A1.1\Indentations,4607213.376255,3455410.032191
4,A1.1 Indentation_005.txt,A1.1\Indentations,NaN,NaN
...,...,...,...,...
224,B2.2 Indentation_073.txt,B2.2\Indentations,4607213.376255,3455410.032191
225,B2.2 Indentation_074.txt,B2.2\Indentations,NaN,NaN
226,B2.2 Indentation_075.txt,B2.2\Indentations,NaN,NaN
227,B2.2 Indentation_076.txt,B2.2\Indentations,NaN,NaN
228,B2.2 Indentation_077.txt,B2.2\Indentations,4607213.376255,3455410.032191

In [18]:
# Remove outliers where E value is more than 1 GPa (1e6 kPa)
results_df = results_df[(results_df["E[eff] (kPa)"] < 1e6) & (results_df["E[v=0.50] (kPa)"] < 1e6)]

# Remove Nan values
results_df = results_df.dropna(subset=["E[eff] (kPa)", "E[v=0.50] (kPa)"])

# Save the results to a CSV file
results_df.to_csv(os.path.join(folder_path, "results.csv"), index=False)

display(results_df)

                         Name             Folder E[eff] (kPa) E[v=0.50] (kPa)
16   A1.1 Indentation_017.txt  A1.1\Indentations      3.08256         2.31192
32   A1.1 Indentation_033.txt  A1.1\Indentations     0.093589        0.070191
34   A1.1 Indentation_035.txt  A1.1\Indentations     0.626815        0.470111
39   A1.1 Indentation_040.txt  A1.1\Indentations     1.783889        1.337917
40   A1.1 Indentation_041.txt  A1.1\Indentations     0.477075        0.357807
46   A1.2 Indentation_006.txt  A1.2\Indentations     5.490882        4.118162
47   A1.2 Indentation_007.txt  A1.2\Indentations     4.655917        3.491938
51   A1.2 Indentation_011.txt  A1.2\Indentations     1.733352        1.300014
52   A1.2 Indentation_012.txt  A1.2\Indentations      2.84009        2.130067
54   A1.2 Indentation_014.txt  A1.2\Indentations     0.283162        0.212371
58   A1.2 Indentation_020.txt  A1.2\Indentations     3.361072        2.520804
59   A1.2 Indentation_021.txt  A1.2\Indentations     3.746417        2.809813
69   B1.1 Indentation_010.txt  B1.1\Indentations     0.506793        0.380095
70   B1.1 Indentation_011.txt  B1.1\Indentations     0.619816        0.464862
72   B1.1 Indentation_013.txt  B1.1\Indentations     0.391368        0.293526
73   B1.1 Indentation_014.txt  B1.1\Indentations     0.116752        0.087564
76   B1.1 Indentation_017.txt  B1.1\Indentations     0.536754        0.402566
77   B1.1 Indentation_018.txt  B1.1\Indentations     0.484773         0.36358
79   B1.1 Indentation_020.txt  B1.1\Indentations      0.78025        0.585188
80   B1.1 Indentation_021.txt  B1.1\Indentations     0.621949        0.466462
82   B1.1 Indentation_023.txt  B1.1\Indentations     0.315093         0.23632
85   B1.1 Indentation_026.txt  B1.1\Indentations     0.761782        0.571337
86   B1.1 Indentation_027.txt  B1.1\Indentations     0.510437        0.382827
90   B1.2 Indentation_004.txt  B1.2\Indentations     1.810131        1.357598
94   B1.2 Indentation_009.txt  B1.2\Indentations     1.223735        0.917801
96   B1.2 Indentation_011.txt  B1.2\Indentations     0.996267          0.7472
97   B1.2 Indentation_012.txt  B1.2\Indentations     0.953319        0.714989
101  B1.2 Indentation_016.txt  B1.2\Indentations     0.493409        0.370057
102  B1.2 Indentation_017.txt  B1.2\Indentations     0.632811        0.474609
116  B1.2 Indentation_031.txt  B1.2\Indentations     0.343774         0.25783
118  B1.2 Indentation_034.txt  B1.2\Indentations     0.150927        0.113196
124  B1.2 Indentation_040.txt  B1.2\Indentations     0.431796        0.323847
125  B1.2 Indentation_041.txt  B1.2\Indentations     0.954185        0.715638
126  B2.1 Indentation_001.txt  B2.1\Indentations    13.982333       10.486749
137  B2.1 Indentation_012.txt  B2.1\Indentations      0.90274        0.677055
149  B2.1 Indentation_024.txt  B2.1\Indentations     0.066002        0.049501
155  B2.2 Indentation_004.txt  B2.2\Indentations     1.238698        0.929024
156  B2.2 Indentation_005.txt  B2.2\Indentations       1.3318         0.99885
160  B2.2 Indentation_009.txt  B2.2\Indentations     2.663104        1.997328
161  B2.2 Indentation_010.txt  B2.2\Indentations     2.385919        1.789439
164  B2.2 Indentation_013.txt  B2.2\Indentations     9.165367        6.874025
165  B2.2 Indentation_014.txt  B2.2\Indentations      0.60845        0.456337
166  B2.2 Indentation_015.txt  B2.2\Indentations     0.876265        0.657198
212  B2.2 Indentation_061.txt  B2.2\Indentations     0.986333         0.73975

In [20]:
# Aggregate the results by folder and calculate the mean and standard deviation for E[eff] and E[v=0.50]
aggregated_df = results_df.groupby("Folder").agg({"E[eff] (kPa)": ["mean"], "E[v=0.50] (kPa)": ["mean"]})

display(aggregated_df)

                  E[eff] (kPa) E[v=0.50] (kPa)
                          mean            mean
Folder
A1.1\Indentations     1.212786        0.909589
A1.2\Indentations     3.158699        2.369024
B1.1\Indentations     0.513252        0.384939
B1.2\Indentations     0.799035        0.599277
B2.1\Indentations     4.983692        3.737768
B2.2\Indentations     2.406992        1.805244